title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
github_username: nighthawkcoders
baseurl: "/student"
# remote_theme: pages-themes/minimal-mistakes@v0.2.0
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
# remote_theme: mmistakes/minimal-mistakes





plugins:
- jekyll-remote-theme
future: true
